version: '2'
services:
  video-yolo:
    build: .
    container_name: video-yolo
    ports:
      - "3000:3000"
    volumes:
      - ./resources:/home/video-yolo/resources
      - ./results:/home/video-yolo/results

  slack-client:
    build: ./slack-client/.
    container_name: slack-client
    links:
      - "video-yolo"
    volumes:
      - ./results:/home/slack-client/results
