version: '2'
services:
  venom:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./resources:/home/venom/resources
      - ./results:/home/venom/results
    restart: always

  angelo:
    build: ./angelo/.
    restart: always
