version: '2'
services:
  video-yolo:
    build: .
    container_name: video-yolo
    ports:
      - "3000:3000"
    volumes:
      - ./resources:/home/video-yolo/resources
      - ./results:/home/video-yolo/results